<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="wfrm_utileria.aspx.vb" Inherits="WAPP_GYMADMIN.wfrm_utileria" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="PanelControl" runat="server" CssClass="panel">
        <table class="style1">
        <tr>
            <td class="style2">
                <asp:TextBox ID="TxtBuscar" runat="server" Width="410px"></asp:TextBox>
            </td>
        </tr>
    </table>
        <br />
        <br />
    <div class="dataGrid">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="Id" 
                    DataSourceID="GymData" ForeColor="#333333" GridLines="None" Height="147px" 
                    Width="417px" AllowPaging="True" AllowSorting="True" 
                    ShowHeaderWhenEmpty="True" 
                        
                        EmptyDataText="Ingresa la categoria de utileria por la que se desea filtrar.">
                    <AlternatingRowStyle BackColor="White" ForeColor="#ff0000" />
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="Nombre" HeaderText="Nombre" 
                            SortExpression="Nombre" />
                        <asp:BoundField DataField="Categoria" HeaderText="Categoria" 
                            SortExpression="Categoria" />
                        <asp:BoundField DataField="Cantidad" HeaderText="Cantidad" 
                            SortExpression="Cantidad" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="Black" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="Red" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="Red" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="Red" />
                </asp:GridView> 
                </div>
                <asp:AccessDataSource ID="GymData" runat="server" 
                    DataFile="~/App_Data/GymData.mdb" 
                    DeleteCommand="DELETE FROM [Utileria] WHERE [Id] = ?" 
                    InsertCommand="INSERT INTO [Utileria] ([Id], [Nombre], [Categoria], [Cantidad]) VALUES (?, ?, ?, ?)" 
                    SelectCommand="SELECT * FROM [Utileria] WHERE ([Categoria] LIKE '%' + ? + '%')" 
                    
                
            
            UpdateCommand="UPDATE [Utileria] SET [Nombre] = ?, [Categoria] = ?, [Cantidad] = ? WHERE [Id] = ?">
                    <DeleteParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                        <asp:Parameter Name="Nombre" Type="String" />
                        <asp:Parameter Name="Categoria" Type="String" />
                        <asp:Parameter Name="Cantidad" Type="Int32" />
                    </InsertParameters>
                    <SelectParameters>
                        <asp:ControlParameter ControlID="TxtBuscar" Name="Categoria" PropertyName="Text" 
                            Type="String" />
                    </SelectParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Nombre" Type="String" />
                        <asp:Parameter Name="Categoria" Type="String" />
                        <asp:Parameter Name="Cantidad" Type="Int32" />
                        <asp:Parameter Name="Id" Type="Int32" />
                    </UpdateParameters>
                </asp:AccessDataSource>
        <br />
    </asp:Panel>   
    </asp:Content>
