<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="wfrm_pagos.aspx.vb" Inherits="WAPP_GYMADMIN.wfrm_pagos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="PanelControl" runat="server" CssClass="panel">
        <table class="style1">
        <tr>
            <td class="style2">
                <asp:TextBox ID="TxtBuscar" runat="server" Width="410px"></asp:TextBox>
            </td>
        </tr>
    </table>
        <br />
        <br />
    <div class="dataGrid">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="Id" 
                    DataSourceID="GymData" ForeColor="#333333" GridLines="None" Height="147px" 
                    Width="417px" AllowPaging="True" AllowSorting="True" 
                    ShowHeaderWhenEmpty="True" 
                        EmptyDataText="Ingrese el nombre del cliente por el que se desea filtrar.">
                    <AlternatingRowStyle BackColor="White" ForeColor="#ff0000" />
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="Nombre_Cliente" HeaderText="Nombre_Cliente" 
                            SortExpression="Nombre_Cliente" />
                        <asp:BoundField DataField="Fecha" HeaderText="Fecha" 
                            SortExpression="Fecha" />
                        <asp:BoundField DataField="Tipo" HeaderText="Tipo" SortExpression="Tipo" />
                        <asp:BoundField DataField="Monto" HeaderText="Monto" 
                            SortExpression="Monto" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="Black" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="Red" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="Red" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="Red" />
                </asp:GridView> 
                </div>
                <asp:AccessDataSource ID="GymData" runat="server" 
                    DataFile="~/App_Data/GymData.mdb" 
                    DeleteCommand="DELETE FROM [Pagos] WHERE [Id] = ?" 
                    InsertCommand="INSERT INTO [Pagos] ([Id], [Nombre_Cliente], [Fecha], [Tipo], [Monto]) VALUES (?, ?, ?, ?, ?)" 
                    SelectCommand="SELECT * FROM [Pagos] WHERE ([Nombre_Cliente] LIKE '%' + ? + '%')" 
                    
                
            UpdateCommand="UPDATE [Pagos] SET [Nombre_Cliente] = ?, [Fecha] = ?, [Tipo] = ?, [Monto] = ? WHERE [Id] = ?">
                    <DeleteParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                        <asp:Parameter Name="Nombre_Cliente" Type="String" />
                        <asp:Parameter Name="Fecha" Type="String" />
                        <asp:Parameter Name="Tipo" Type="String" />
                        <asp:Parameter Name="Monto" Type="Decimal" />
                    </InsertParameters>
                    <SelectParameters>
                        <asp:ControlParameter ControlID="TxtBuscar" Name="Nombre_Cliente" PropertyName="Text" 
                            Type="String" />
                    </SelectParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Nombre_Cliente" Type="String" />
                        <asp:Parameter Name="Fecha" Type="String" />
                        <asp:Parameter Name="Tipo" Type="String" />
                        <asp:Parameter Name="Monto" Type="Decimal" />
                        <asp:Parameter Name="Id" Type="Int32" />
                    </UpdateParameters>
                </asp:AccessDataSource>
        <br />
    </asp:Panel>   
</asp:Content>
