<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="wfrm_admin_pagos.aspx.vb" Inherits="WAPP_GYMADMIN.wfrm_admin_pagos" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <asp:Panel ID="PanelControl" runat="server" CssClass="panel">
        <table class="style1">
        <tr>
            <td class="style2">
                <asp:Label ID="Label1" runat="server" Text="Nombre_cliente"></asp:Label>
            </td>
            <td class="style2">
                <asp:TextBox ID="TxtNombre" runat="server"></asp:TextBox>
            </td>
            <td class="style2">
                <asp:Label ID="Label2" runat="server" Text="Fecha"></asp:Label>
            </td>
            <td class="style2">
                <asp:TextBox ID="TxtFecha" runat="server"></asp:TextBox>
            </td>
            <td class="style2">
                <asp:Label ID="Label3" runat="server" Text="Tipo"></asp:Label>
            </td>
            <td class="style3">
                <asp:TextBox ID="TxtTipo" runat="server"></asp:TextBox>
            </td>
            <td class="style10">
                <asp:Label ID="Label4" runat="server" Text="Monto"></asp:Label>
            </td>
            <td class="style3">
                <asp:TextBox ID="TxtMonto" runat="server"></asp:TextBox>
            </td>
            <td class="style3">
                <asp:Button ID="BtnGuardar" runat="server" class="Btn" Text="Guardar"/>
            </td>
        </tr>
    </table>
        <br />
        <br />
    <div class="dataGrid">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="Id" 
                    DataSourceID="GymData" ForeColor="#333333" GridLines="None" Height="225px" 
                    Width="417px" AllowPaging="True" AllowSorting="True" 
                    ShowHeaderWhenEmpty="True">
                    <AlternatingRowStyle BackColor="White" ForeColor="#ff0000" />
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="Nombre_Cliente" HeaderText="Nombre_Cliente" 
                            SortExpression="Nombre_Cliente" />
                        <asp:BoundField DataField="Fecha" HeaderText="Fecha" 
                            SortExpression="Fecha" />
                        <asp:BoundField DataField="Tipo" HeaderText="Tipo" SortExpression="Tipo" />
                        <asp:BoundField DataField="Monto" HeaderText="Monto" 
                            SortExpression="Monto" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="Black" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="Red" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="Red" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="Red" />
                </asp:GridView> 
                </div>
                <asp:AccessDataSource ID="GymData" runat="server" 
                    DataFile="~/App_Data/GymData.mdb" 
                    DeleteCommand="DELETE FROM [Pagos] WHERE [Id] = ?" 
                    InsertCommand="INSERT INTO [Pagos] ([Id], [Nombre_Cliente], [Fecha], [Tipo], [Monto]) VALUES (?, ?, ?, ?, ?)" 
                    SelectCommand="SELECT * FROM [Pagos]" 
                    
            UpdateCommand="UPDATE [Pagos] SET [Nombre_Cliente] = ?, [Fecha] = ?, [Tipo] = ?, [Monto] = ? WHERE [Id] = ?">
                    <DeleteParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                        <asp:Parameter Name="Nombre_Cliente" Type="String" />
                        <asp:Parameter Name="Fecha" Type="String" />
                        <asp:Parameter Name="Tipo" Type="String" />
                        <asp:Parameter Name="Monto" Type="Decimal" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Nombre_Cliente" Type="String" />
                        <asp:Parameter Name="Fecha" Type="String" />
                        <asp:Parameter Name="Tipo" Type="String" />
                        <asp:Parameter Name="Monto" Type="Decimal" />
                        <asp:Parameter Name="Id" Type="Int32" />
                    </UpdateParameters>
                </asp:AccessDataSource>
        <br />
    </asp:Panel>  
</asp:Content>
