<%@ Page Title="" Language="vb" AutoEventWireup="false" MasterPageFile="~/Site.Master" CodeBehind="wfrm_cliente.aspx.vb" Inherits="WAPP_GYMADMIN.wfrm_cliente" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
        <asp:Panel ID="PanelControl" runat="server" CssClass="panel">
        <table class="style1">
        <tr>
            <td class="style2">
                <asp:TextBox ID="TxtBuscar" runat="server" Width="410px"></asp:TextBox>
            </td>
        </tr>
    </table>
        <br />
        <br />
    <div class="dataGrid">
                    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    AutoGenerateSelectButton="True" CellPadding="4" DataKeyNames="Id" 
                    DataSourceID="GymData" ForeColor="#333333" GridLines="None" Height="147px" 
                    Width="417px" AllowPaging="True" AllowSorting="True" 
                    ShowHeaderWhenEmpty="True" 
                        EmptyDataText="Ingrese en la barra de busqueda el apellido por el que se desea filtrar.">
                    <AlternatingRowStyle BackColor="White" ForeColor="#ff0000" />
                    <Columns>
                        <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" 
                            ReadOnly="True" SortExpression="Id" />
                        <asp:BoundField DataField="Nombre" HeaderText="Nombre" 
                            SortExpression="Nombre" />
                        <asp:BoundField DataField="Apellido" HeaderText="Apellido" 
                            SortExpression="Apellido" />
                        <asp:BoundField DataField="Edad" HeaderText="Edad" SortExpression="Edad" />
                        <asp:BoundField DataField="Cedula" HeaderText="Cedula" 
                            SortExpression="Cedula" />
                    </Columns>
                    <EditRowStyle BackColor="#999999" />
                    <FooterStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="Black" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="Red" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#E9E7E2" />
                    <SortedAscendingHeaderStyle BackColor="Red" />
                    <SortedDescendingCellStyle BackColor="#FFFDF8" />
                    <SortedDescendingHeaderStyle BackColor="Red" />
                </asp:GridView> 
                </div>
                <asp:AccessDataSource ID="GymData" runat="server" 
                    DataFile="~/App_Data/GymData.mdb" 
                    DeleteCommand="DELETE FROM [Cliente] WHERE [Id] = ?" 
                    InsertCommand="INSERT INTO [Cliente] ([Id], [Nombre], [Apellido], [Edad], [Cedula]) VALUES (?, ?, ?, ?, ?)" 
                    SelectCommand="SELECT * FROM [Cliente] WHERE ([Apellido] LIKE '%' + ? + '%')" 
                    
                UpdateCommand="UPDATE [Cliente] SET [Nombre] = ?, [Apellido] = ?, [Edad] = ?, [Cedula] = ? WHERE [Id] = ?">
                    <DeleteParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Id" Type="Int32" />
                        <asp:Parameter Name="Nombre" Type="String" />
                        <asp:Parameter Name="Apellido" Type="String" />
                        <asp:Parameter Name="Edad" Type="Int32" />
                        <asp:Parameter Name="Cedula" Type="String" />
                    </InsertParameters>
                    <SelectParameters>
                        <asp:ControlParameter ControlID="TxtBuscar" Name="Apellido" PropertyName="Text" 
                            Type="String" />
                    </SelectParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Nombre" Type="String" />
                        <asp:Parameter Name="Apellido" Type="String" />
                        <asp:Parameter Name="Edad" Type="Int32" />
                        <asp:Parameter Name="Cedula" Type="String" />
                        <asp:Parameter Name="Id" Type="Int32" />
                    </UpdateParameters>
                </asp:AccessDataSource>
        <br />
    </asp:Panel>     
    </asp:Content>
