'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'
'     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
'     el código se vuelve a generar.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Register

    '''<summary>
    '''Control RegisterUser.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RegisterUser As Global.System.Web.UI.WebControls.CreateUserWizard

    '''<summary>
    '''Control RegisterUserWizardStep.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents RegisterUserWizardStep As Global.System.Web.UI.WebControls.CreateUserWizardStep
End Class
